server:
  port: 8082
spring:
  application:
    name: post-service
  jpa:
    show-sql: true
    hibernate.ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        default_schema: post
  datasource:
    url: jdbc:postgresql://localhost:5432/sm
    username: postgres
    password: 12345
  resources:
    add-mappings: false
  jackson:
    date-format: dd-MM-yyyy
logging:
  file: sm-post-service.log